# Solar Energy Storage Project

## Problem:

Find the best location of the three selected areas in the United States where we can best predict the GHI (Global Horizontal Irradiation), key indicator for energy storage potential, with weather indicators of the past 20 years to be able to install solar panels. These points were selected by the company based on historical average values of GHI, and land availability and cost. The data is provided by NASA of the POWER Project over the past 20 years with an hourly frequency.

## Data:


### About the Power project: 

NASA's goal in Earth science is to observe, understand, and model the Earth system to discover how it is changing, to better predict change, and to understand the consequences for life on Earth. The Applied Sciences Program, within the Science Mission Directorate (which replaced both the Office of Earth Science and the Office of Space Science), serves NASA and Society by expanding and accelerating the realization of societal and economic benefits from Earth science, information, and technology research and development.

The Prediction Of Worldwide Energy Resources (POWER) project was initiated to improve upon the current renewable energy data set and to create new data sets from new satellite systems. The POWER project targets three user communities: (1) Renewable Energy, (2) Sustainable Buildings, and (3) Agroclimatology.


### Locations selected:

Lat/Lat of Selected Locations in US:

South Arizona:        32.7805 / -112.8105

South California:     33.3146 / -115.2055

South New Mexico:     32.3175 / -107.7129      



### Variables included:

ALLSKY_SFC_SW_DWN (GHI): All Sky Surface Shortwave Downward Irradiance
The total solar irradiance incident (direct plus diffuse) on a horizontal plane at the surface of the earth under all sky conditions. An alternative term for the total solar irradiance is the "Global Horizontal Irradiance" or GHI.

CLRSKY_SFC_PAR_TOT: Clear Sky Surface PAR Total
The total Photosynthetically Active Radiation (PAR) incident on a horizontal plane at the surface of the earth under clear sky conditions.

ALLSKY_SFC_UV_INDEX: All Sky Surface UV Index
The ultraviolet radiation exposure index.

CLRSKY_SFC_SW_DWN: Clear Sky Surface Shortwave Downward Irradiance
The total solar irradiance incident (direct plus diffuse) on a horizontal plane at the surface of the earth under clear sky conditions. An alternative term for the total solar irradiance is the "Global Horizontal Irradiance" or GHI.

WS2M: Wind Speed at 2 Meters
The average of wind speed at 2 meters above the surface of the earth.

T2M: Temperature at 2 Meters
The average air (dry bulb) temperature at 2 meters above the surface of the earth.

T2MDEW: Dew/Frost Point at 2 Meters
The dew/frost point temperature at 2 meters above the surface of the earth.

RH2M: Relative Humidity at 2 Meters
The ratio of actual partial pressure of water vapor to the partial pressure at saturation, expressed in percent.

PRECTOTCORR: Precipitation Corrected
The bias corrected average of total precipitation at the surface of the earth in water mass (includes water content in snow).

PS: Surface Pressure
The average of surface pressure at the surface of the earth.

WS10M: Wind Speed at 10 Meters
The average of wind speed at 10 meters above the surface of the earth.

WS50M: Wind Speed at 50 Meters
The average of wind speed at 50 meters above the surface of the earth.



Link: https://power.larc.nasa.gov/data-access-viewer/

In [76]:
#import pandas, numpy, matlab, seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import tables

warnings.filterwarnings('ignore')


# Data Wrangling 

Import data by location, the hourly data had the limitation of importing up to 10 years of data and only 5 variables at a time, so I needed to break up the data into different files and then needed to concatenate and merge the data to make 1 dataframe.

In [77]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2003 to 2013 for first 5 columns

# Define the number of header lines
header_lines = 13

df1 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz_POWER_Point_Hourly_20031101_20131031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [78]:
# Step 2: add

# Add column for state name
df1['STATE'] = 'Arizona'
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87672 non-null  int64  
 1   MO                   87672 non-null  int64  
 2   DY                   87672 non-null  int64  
 3   HR                   87672 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    87672 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   87672 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  87672 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87672 non-null  float64
 8   WS2M                 87672 non-null  float64
 9   STATE                87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [79]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2013 to 2023

# Define the number of header lines
header_lines = 13

ari2 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz_POWER_Point_Hourly_20131101_20231031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [80]:
# Step 2: add

# Take a look at the info and add column for state name
ari2['STATE'] = 'Arizona'
ari2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87648 non-null  int64  
 1   MO                   87648 non-null  int64  
 2   DY                   87648 non-null  int64  
 3   HR                   87648 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    87648 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   87648 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  87648 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87648 non-null  float64
 8   WS2M                 87648 non-null  float64
 9   STATE                87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [81]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df1 = pd.concat([df1, ari2], ignore_index=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [82]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2003 to 2013 for following 5 columns

# Define the number of header lines
header_lines = 13

ari3 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz2_POWER_Point_Hourly_20031101_20131031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [83]:
# Step 2: add

# Take a look at the info and add column for state name
ari3['STATE'] = 'Arizona'
ari3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87672 non-null  int64  
 1   MO           87672 non-null  int64  
 2   DY           87672 non-null  int64  
 3   HR           87672 non-null  int64  
 4   T2M          87672 non-null  float64
 5   T2MDEW       87672 non-null  float64
 6   RH2M         87672 non-null  float64
 7   PRECTOTCORR  87672 non-null  float64
 8   PS           87672 non-null  float64
 9   STATE        87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [84]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2013 to 2023 for following 5 columns

# Define the number of header lines
header_lines = 13

ari4 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz2_POWER_Point_Hourly_20131101_20231031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [85]:
# Step 2: add

# Take a look at the info and add column for state name
ari4['STATE'] = 'Arizona'
ari4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87648 non-null  int64  
 1   MO           87648 non-null  int64  
 2   DY           87648 non-null  int64  
 3   HR           87648 non-null  int64  
 4   T2M          87648 non-null  float64
 5   T2MDEW       87648 non-null  float64
 6   RH2M         87648 non-null  float64
 7   PRECTOTCORR  87648 non-null  float64
 8   PS           87648 non-null  float64
 9   STATE        87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [86]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df2 = pd.concat([ari3, ari4], ignore_index=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   YEAR         175320 non-null  int64  
 1   MO           175320 non-null  int64  
 2   DY           175320 non-null  int64  
 3   HR           175320 non-null  int64  
 4   T2M          175320 non-null  float64
 5   T2MDEW       175320 non-null  float64
 6   RH2M         175320 non-null  float64
 7   PRECTOTCORR  175320 non-null  float64
 8   PS           175320 non-null  float64
 9   STATE        175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [87]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df1 = pd.merge(df1, df2, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df1.head()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  16               15.9                6.48   
1  2003  10  31  17                0.0                0.00   
2  2003  10  31  18                0.0                0.00   
3  2003  10  31  19                0.0                0.00   
4  2003  10  31  20                0.0                0.00   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M    STATE    T2M  T2MDEW  \
0                 0.02              15.77  5.09  Arizona  22.40    7.67   
1                 0.00               0.00  3.71  Arizona  20.98    8.09   
2                 0.00               0.00  2.62  Arizona  19.93    8.45   
3                 0.00               0.00  1.94  Arizona  19.12    8.76   
4                 0.00               0.00  1.51  Arizona  18.56    9.12   

    RH2M  PRECTOTCORR     PS  
0  38.69          0.0  96.13  
1  43.38          0.0  96.19  
2  47.50          0.0  96.25  
3  51.06          0.0  96.30  
4  54.19          0.0  96.32

In [88]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2003 to 2013 for last 2 columns

# Define the number of header lines
header_lines = 10

ari5 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz3_POWER_Point_Hourly_20031101_20131031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [89]:
# Step 2: add

# Take a look at the info and add column for state name
ari5['STATE'] = 'Arizona'
ari5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87672 non-null  int64  
 1   MO      87672 non-null  int64  
 2   DY      87672 non-null  int64  
 3   HR      87672 non-null  int64  
 4   WS10M   87672 non-null  float64
 5   WS50M   87672 non-null  float64
 6   STATE   87672 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [90]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# Arizona data from 2013 to 2023 for last 2 columns

# Define the number of header lines
header_lines = 10

ari6 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SAriz3_POWER_Point_Hourly_20131101_20231031_032d7805N_112d8105W_LST.csv', skiprows=header_lines)

In [91]:
# Step 2: add

# Take a look at the info and add column for state name
ari6['STATE'] = 'Arizona'
ari6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87648 non-null  int64  
 1   MO      87648 non-null  int64  
 2   DY      87648 non-null  int64  
 3   HR      87648 non-null  int64  
 4   WS10M   87648 non-null  float64
 5   WS50M   87648 non-null  float64
 6   STATE   87648 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [92]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df3 = pd.concat([ari5, ari6], ignore_index=True)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   YEAR    175320 non-null  int64  
 1   MO      175320 non-null  int64  
 2   DY      175320 non-null  int64  
 3   HR      175320 non-null  int64  
 4   WS10M   175320 non-null  float64
 5   WS50M   175320 non-null  float64
 6   STATE   175320 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 9.4+ MB


In [93]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df_ariz = pd.merge(df1, df3, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df_ariz.info()
df_ariz.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
 10  T2M                  175320 non-null  float64
 11  T2MDEW               175320 non-null  float64
 12  RH2M                 175320 non-null  float64
 13  PRECTOTCORR          175320 non-null  float64
 14  PS                   175320 non-null  float64
 15  WS10M            

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  16               15.9                6.48   
1  2003  10  31  17                0.0                0.00   
2  2003  10  31  18                0.0                0.00   
3  2003  10  31  19                0.0                0.00   
4  2003  10  31  20                0.0                0.00   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M    STATE    T2M  T2MDEW  \
0                 0.02              15.77  5.09  Arizona  22.40    7.67   
1                 0.00               0.00  3.71  Arizona  20.98    8.09   
2                 0.00               0.00  2.62  Arizona  19.93    8.45   
3                 0.00               0.00  1.94  Arizona  19.12    8.76   
4                 0.00               0.00  1.51  Arizona  18.56    9.12   

    RH2M  PRECTOTCORR     PS  WS10M  WS50M  
0  38.69          0.0  96.13   6.99   9.18  
1  43.38          0.0  96.19   5.23   7.72  
2  47.50          0.0  96.25   3.80   6.35  
3  51.06          0.0  96.30   2.95   5.56  
4  54.19          0.0  96.32   2.45   4.83

### Next state: California, repeat steps from above

In [94]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2003 to 2013 for first 5 columns

# Define the number of header lines
header_lines = 13

cali1 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali_POWER_Point_Hourly_20031101_20131031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [95]:
# Step 2: add

# Add column for state name
cali1['STATE'] = 'California'
cali1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87672 non-null  int64  
 1   MO                   87672 non-null  int64  
 2   DY                   87672 non-null  int64  
 3   HR                   87672 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    87672 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   87672 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  87672 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87672 non-null  float64
 8   WS2M                 87672 non-null  float64
 9   STATE                87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [96]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2013 to 2023

# Define the number of header lines
header_lines = 13

cali2 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali_POWER_Point_Hourly_20131101_20231031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [97]:
# Step 2: add

# Take a look at the info and add column for state name
cali2['STATE'] = 'California'
cali2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87648 non-null  int64  
 1   MO                   87648 non-null  int64  
 2   DY                   87648 non-null  int64  
 3   HR                   87648 non-null  int64  
 4   ALLSKY_SFC_UV_INDEX  87648 non-null  float64
 5   ALLSKY_SFC_SW_DWN    87648 non-null  float64
 6   CLRSKY_SFC_PAR_TOT   87648 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87648 non-null  float64
 8   WS2M                 87648 non-null  float64
 9   STATE                87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [98]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_2 = pd.concat([cali1, cali2], ignore_index=True)
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [99]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2003 to 2013 for following 5 columns

# Define the number of header lines
header_lines = 13

cali3 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali2_POWER_Point_Hourly_20031101_20131031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [100]:
# Step 2: add

# Take a look at the info and add column for state name
cali3['STATE'] = 'California'
cali3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87672 non-null  int64  
 1   MO           87672 non-null  int64  
 2   DY           87672 non-null  int64  
 3   HR           87672 non-null  int64  
 4   T2M          87672 non-null  float64
 5   T2MDEW       87672 non-null  float64
 6   RH2M         87672 non-null  float64
 7   PRECTOTCORR  87672 non-null  float64
 8   PS           87672 non-null  float64
 9   STATE        87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [101]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2013 to 2023 for following 5 columns

# Define the number of header lines
header_lines = 13

cali4 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali2_POWER_Point_Hourly_20131101_20231031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [102]:
# Step 2: add

# Take a look at the info and add column for state name
cali4['STATE'] = 'California'
cali4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87648 non-null  int64  
 1   MO           87648 non-null  int64  
 2   DY           87648 non-null  int64  
 3   HR           87648 non-null  int64  
 4   T2M          87648 non-null  float64
 5   T2MDEW       87648 non-null  float64
 6   RH2M         87648 non-null  float64
 7   PRECTOTCORR  87648 non-null  float64
 8   PS           87648 non-null  float64
 9   STATE        87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [103]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_3 = pd.concat([cali3, cali4], ignore_index=True)
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   YEAR         175320 non-null  int64  
 1   MO           175320 non-null  int64  
 2   DY           175320 non-null  int64  
 3   HR           175320 non-null  int64  
 4   T2M          175320 non-null  float64
 5   T2MDEW       175320 non-null  float64
 6   RH2M         175320 non-null  float64
 7   PRECTOTCORR  175320 non-null  float64
 8   PS           175320 non-null  float64
 9   STATE        175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [104]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df_4 = pd.merge(df_2, df_3, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df_4.head()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  16              36.11               14.42   
1  2003  10  31  17               0.00                0.00   
2  2003  10  31  18               0.00                0.00   
3  2003  10  31  19               0.00                0.00   
4  2003  10  31  20               0.00                0.00   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M       STATE    T2M  T2MDEW  \
0                 0.02              37.65  3.15  California  19.30   -0.83   
1                 0.00               0.00  1.85  California  16.33   -0.57   
2                 0.00               0.00  2.52  California  15.65    0.37   
3                 0.00               0.00  2.95  California  14.73    1.52   
4                 0.00               0.00  2.85  California  13.75    2.55   

    RH2M  PRECTOTCORR     PS  
0  25.62          0.0  97.48  
1  31.50          0.0  97.52  
2  35.31          0.0  97.60  
3  40.75          0.0  97.66  
4  46.88          0.0  97.69

In [105]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2003 to 2013 for last 2 columns

# Define the number of header lines
header_lines = 10

cali5 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali3_POWER_Point_Hourly_20031101_20131031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [106]:
# Step 2: add

# Take a look at the info and add column for state name
cali5['STATE'] = 'California'
cali5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87672 non-null  int64  
 1   MO      87672 non-null  int64  
 2   DY      87672 non-null  int64  
 3   HR      87672 non-null  int64  
 4   WS10M   87672 non-null  float64
 5   WS50M   87672 non-null  float64
 6   STATE   87672 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [107]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# California data from 2013 to 2023 for last 2 columns

# Define the number of header lines
header_lines = 10

cali6 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SCali3_POWER_Point_Hourly_20131101_20231031_033d3146N_115d2055W_LST.csv', skiprows=header_lines)

In [108]:
# Step 2: add

# Take a look at the info and add column for state name
cali6['STATE'] = 'California'
cali6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87648 non-null  int64  
 1   MO      87648 non-null  int64  
 2   DY      87648 non-null  int64  
 3   HR      87648 non-null  int64  
 4   WS10M   87648 non-null  float64
 5   WS50M   87648 non-null  float64
 6   STATE   87648 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [109]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_5 = pd.concat([cali5, cali6], ignore_index=True)
df_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   YEAR    175320 non-null  int64  
 1   MO      175320 non-null  int64  
 2   DY      175320 non-null  int64  
 3   HR      175320 non-null  int64  
 4   WS10M   175320 non-null  float64
 5   WS50M   175320 non-null  float64
 6   STATE   175320 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 9.4+ MB


In [110]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df_cali = pd.merge(df_4, df_5, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df_cali.info()
df_cali.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
 10  T2M                  175320 non-null  float64
 11  T2MDEW               175320 non-null  float64
 12  RH2M                 175320 non-null  float64
 13  PRECTOTCORR          175320 non-null  float64
 14  PS                   175320 non-null  float64
 15  WS10M            

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  16              36.11               14.42   
1  2003  10  31  17               0.00                0.00   
2  2003  10  31  18               0.00                0.00   
3  2003  10  31  19               0.00                0.00   
4  2003  10  31  20               0.00                0.00   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M       STATE    T2M  T2MDEW  \
0                 0.02              37.65  3.15  California  19.30   -0.83   
1                 0.00               0.00  1.85  California  16.33   -0.57   
2                 0.00               0.00  2.52  California  15.65    0.37   
3                 0.00               0.00  2.95  California  14.73    1.52   
4                 0.00               0.00  2.85  California  13.75    2.55   

    RH2M  PRECTOTCORR     PS  WS10M  WS50M  
0  25.62          0.0  97.48   4.36   6.30  
1  31.50          0.0  97.52   3.12   6.36  
2  35.31          0.0  97.60   3.88   7.02  
3  40.75          0.0  97.66   4.39   7.24  
4  46.88          0.0  97.69   4.26   7.16

### Next state: New Mexico, repeat steps from above

In [111]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2003 to 2013 for first 5 columns

# Define the number of header lines
header_lines = 13

nmex1 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM_POWER_Point_Hourly_20031101_20131031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [112]:
# Step 2: add

# Add column for state name
nmex1['STATE'] = 'NewMexico'
nmex1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87672 non-null  int64  
 1   MO                   87672 non-null  int64  
 2   DY                   87672 non-null  int64  
 3   HR                   87672 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    87672 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   87672 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  87672 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87672 non-null  float64
 8   WS2M                 87672 non-null  float64
 9   STATE                87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [113]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2013 to 2023

# Define the number of header lines
header_lines = 13

nmex2 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM_POWER_Point_Hourly_20131101_20231031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [114]:
# Step 2: add

# Take a look at the info and add column for state name
nmex2['STATE'] = 'NewMexico'
nmex2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 87648 non-null  int64  
 1   MO                   87648 non-null  int64  
 2   DY                   87648 non-null  int64  
 3   HR                   87648 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    87648 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   87648 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  87648 non-null  float64
 7   CLRSKY_SFC_SW_DWN    87648 non-null  float64
 8   WS2M                 87648 non-null  float64
 9   STATE                87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [115]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_6 = pd.concat([nmex1, nmex2], ignore_index=True)
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [116]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2003 to 2013 for following 5 columns

# Define the number of header lines
header_lines = 13

nmex3 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM2_POWER_Point_Hourly_20031101_20131031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [117]:
# Step 2: add

# Take a look at the info and add column for state name
nmex3['STATE'] = 'NewMexico'
nmex3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87672 non-null  int64  
 1   MO           87672 non-null  int64  
 2   DY           87672 non-null  int64  
 3   HR           87672 non-null  int64  
 4   T2M          87672 non-null  float64
 5   T2MDEW       87672 non-null  float64
 6   RH2M         87672 non-null  float64
 7   PRECTOTCORR  87672 non-null  float64
 8   PS           87672 non-null  float64
 9   STATE        87672 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [118]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2013 to 2023 for following 5 columns

# Define the number of header lines
header_lines = 13

nmex4 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM2_POWER_Point_Hourly_20131101_20231031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [119]:
# Step 2: add

# Take a look at the info and add column for state name
nmex4['STATE'] = 'NewMexico'
nmex4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   YEAR         87648 non-null  int64  
 1   MO           87648 non-null  int64  
 2   DY           87648 non-null  int64  
 3   HR           87648 non-null  int64  
 4   T2M          87648 non-null  float64
 5   T2MDEW       87648 non-null  float64
 6   RH2M         87648 non-null  float64
 7   PRECTOTCORR  87648 non-null  float64
 8   PS           87648 non-null  float64
 9   STATE        87648 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 6.7+ MB


In [120]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_7 = pd.concat([nmex3, nmex4], ignore_index=True)
df_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   YEAR         175320 non-null  int64  
 1   MO           175320 non-null  int64  
 2   DY           175320 non-null  int64  
 3   HR           175320 non-null  int64  
 4   T2M          175320 non-null  float64
 5   T2MDEW       175320 non-null  float64
 6   RH2M         175320 non-null  float64
 7   PRECTOTCORR  175320 non-null  float64
 8   PS           175320 non-null  float64
 9   STATE        175320 non-null  object 
dtypes: float64(5), int64(4), object(1)
memory usage: 13.4+ MB


In [121]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df_8 = pd.merge(df_6, df_7, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df_8.head()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  17               7.78                 1.2   
1  2003  10  31  18               0.00                 0.0   
2  2003  10  31  19               0.00                 0.0   
3  2003  10  31  20               0.00                 0.0   
4  2003  10  31  21               0.00                 0.0   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M      STATE    T2M  T2MDEW  \
0                  0.0               3.15  1.86  NewMexico  19.33   -1.03   
1                  0.0               0.00  1.83  NewMexico  17.81   -1.35   
2                  0.0               0.00  1.78  NewMexico  17.30   -1.49   
3                  0.0               0.00  1.69  NewMexico  16.76   -1.33   
4                  0.0               0.00  1.49  NewMexico  15.76   -0.92   

    RH2M  PRECTOTCORR     PS  
0  25.25          0.0  85.21  
1  27.06          0.0  85.24  
2  27.75          0.0  85.28  
3  29.00          0.0  85.31  
4  31.94          0.0  85.33

In [122]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2003 to 2013 for last 2 columns

# Define the number of header lines
header_lines = 10

nmex5 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM3_POWER_Point_Hourly_20031101_20131031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [123]:
# Step 2: add

# Take a look at the info and add column for state name
nmex5['STATE'] = 'NewMexico'
nmex5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87672 entries, 0 to 87671
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87672 non-null  int64  
 1   MO      87672 non-null  int64  
 2   DY      87672 non-null  int64  
 3   HR      87672 non-null  int64  
 4   WS10M   87672 non-null  float64
 5   WS50M   87672 non-null  float64
 6   STATE   87672 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [124]:
# Step 1: import

# Read in file. Source data: Nasa, The Power Project

# New Mexico data from 2013 to 2023 for last 2 columns

# Define the number of header lines
header_lines = 10

nmex6 = pd.read_csv('/Users/claudiazaffaroni/Desktop/Springboard_Data_Science_Course/Capstone_3/SNewM3_POWER_Point_Hourly_20131101_20231031_032d3175N_107d7129W_LST.csv', skiprows=header_lines)

In [125]:
# Step 2: add

# Take a look at the info and add column for state name
nmex6['STATE'] = 'NewMexico'
nmex6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87648 entries, 0 to 87647
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YEAR    87648 non-null  int64  
 1   MO      87648 non-null  int64  
 2   DY      87648 non-null  int64  
 3   HR      87648 non-null  int64  
 4   WS10M   87648 non-null  float64
 5   WS50M   87648 non-null  float64
 6   STATE   87648 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 4.7+ MB


In [126]:
# Step 3: concatenate rows

# Concatenate the two DataFrames vertically (along rows)
df_9 = pd.concat([nmex5, nmex6], ignore_index=True)
df_9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   YEAR    175320 non-null  int64  
 1   MO      175320 non-null  int64  
 2   DY      175320 non-null  int64  
 3   HR      175320 non-null  int64  
 4   WS10M   175320 non-null  float64
 5   WS50M   175320 non-null  float64
 6   STATE   175320 non-null  object 
dtypes: float64(2), int64(4), object(1)
memory usage: 9.4+ MB


In [127]:
# Step 4: merge columns

# Merge DataFrames on State, Year, Month, Day and Hour to have all variables in 1 dataframe

df_nmex = pd.merge(df_8, df_9, on=['STATE', 'YEAR', 'MO', 'DY', 'HR'])
df_nmex.info()
df_nmex.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175320 entries, 0 to 175319
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 175320 non-null  int64  
 1   MO                   175320 non-null  int64  
 2   DY                   175320 non-null  int64  
 3   HR                   175320 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    175320 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   175320 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  175320 non-null  float64
 7   CLRSKY_SFC_SW_DWN    175320 non-null  float64
 8   WS2M                 175320 non-null  float64
 9   STATE                175320 non-null  object 
 10  T2M                  175320 non-null  float64
 11  T2MDEW               175320 non-null  float64
 12  RH2M                 175320 non-null  float64
 13  PRECTOTCORR          175320 non-null  float64
 14  PS                   175320 non-null  float64
 15  WS10M            

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  17               7.78                 1.2   
1  2003  10  31  18               0.00                 0.0   
2  2003  10  31  19               0.00                 0.0   
3  2003  10  31  20               0.00                 0.0   
4  2003  10  31  21               0.00                 0.0   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M      STATE    T2M  T2MDEW  \
0                  0.0               3.15  1.86  NewMexico  19.33   -1.03   
1                  0.0               0.00  1.83  NewMexico  17.81   -1.35   
2                  0.0               0.00  1.78  NewMexico  17.30   -1.49   
3                  0.0               0.00  1.69  NewMexico  16.76   -1.33   
4                  0.0               0.00  1.49  NewMexico  15.76   -0.92   

    RH2M  PRECTOTCORR     PS  WS10M  WS50M  
0  25.25          0.0  85.21   3.40   7.11  
1  27.06          0.0  85.24   3.45   7.28  
2  27.75          0.0  85.28   3.34   7.09  
3  29.00          0.0  85.31   3.19   6.76  
4  31.94          0.0  85.33   3.03   6.09

In [128]:
# Check to see that the state value is unique for each dataset of aggregated data.
state_ariz = df_ariz['STATE'].unique()
state_cali = df_cali['STATE'].unique()
state_nmex = df_nmex['STATE'].unique()

# Print the unique values
print(state_ariz, state_cali, state_nmex)

['Arizona'] ['California'] ['NewMexico']


In [129]:
# Check to see that the max and min values for YEAR are correct.
max_year_ariz = df_ariz['YEAR'].max()
min_year_ariz = df_ariz['YEAR'].min()

max_year_cali = df_cali['YEAR'].max()
min_year_cali = df_cali['YEAR'].min()

max_year_nmex = df_nmex['YEAR'].max()
min_year_nmex = df_nmex['YEAR'].min()

# Print the max and min values
print(max_year_ariz, min_year_ariz)
print(max_year_cali, min_year_cali)
print(max_year_nmex, min_year_nmex) 




2023 2003
2023 2003
2023 2003


The min year of 2003 and max year of 2023 are what I expected from all 3 dataframes.

In [354]:
# Now we need to concatenate the 3 dataframes of the 3 locations into 1

# Concatenate the three DataFrames vertically (along rows)
df = pd.concat([df_ariz, df_cali, df_nmex], ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525960 entries, 0 to 525959
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 525960 non-null  int64  
 1   MO                   525960 non-null  int64  
 2   DY                   525960 non-null  int64  
 3   HR                   525960 non-null  int64  
 4   ALLSKY_SFC_SW_DWN    525960 non-null  float64
 5   CLRSKY_SFC_PAR_TOT   525960 non-null  float64
 6   ALLSKY_SFC_UV_INDEX  525960 non-null  float64
 7   CLRSKY_SFC_SW_DWN    525960 non-null  float64
 8   WS2M                 525960 non-null  float64
 9   STATE                525960 non-null  object 
 10  T2M                  525960 non-null  float64
 11  T2MDEW               525960 non-null  float64
 12  RH2M                 525960 non-null  float64
 13  PRECTOTCORR          525960 non-null  float64
 14  PS                   525960 non-null  float64
 15  WS10M            

#### End of concatenation of all datasets 

In [355]:
#Call the describe method on df to see a summary of the data, including count, mean, std, min and max

df.describe()

YEAR             MO             DY             HR  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean     2013.331090       6.522930      15.729637      11.500000   
std         5.778417       3.448706       8.800100       6.922193   
min      2003.000000       1.000000       1.000000       0.000000   
25%      2008.000000       4.000000       8.000000       5.750000   
50%      2013.000000       7.000000      16.000000      11.500000   
75%      2018.000000      10.000000      23.000000      17.250000   
max      2023.000000      12.000000      31.000000      23.000000   

       ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  ALLSKY_SFC_UV_INDEX  \
count      525960.000000       525960.000000        525960.000000   
mean          224.936379           99.053385           -17.001283   
std           357.748778          208.190129           135.416708   
min          -999.000000         -999.000000          -999.000000   
25%             0.000000            0.000000             0.000000   
50%             9.400000            2.770000             0.000000   
75%           489.825000          243.080000             2.350000   
max          1084.630000          471.120000            14.580000   

       CLRSKY_SFC_SW_DWN           WS2M            T2M         T2MDEW  \
count      525960.000000  525960.000000  525960.000000  525960.000000   
mean          245.863993       2.616128      20.575514       1.835372   
std           376.746138       1.646024      10.702683       8.347475   
min          -999.000000       0.010000     -15.770000     -25.220000   
25%             0.000000       1.380000      12.370000      -4.430000   
50%             7.750000       2.170000      20.390000       1.220000   
75%           551.500000       3.490000      28.570000       8.020000   
max          1113.900000      14.810000      50.220000      25.850000   

                RH2M    PRECTOTCORR             PS          WS10M  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean       35.020759       0.019436      93.187504       3.764486   
std        21.047573       0.131012       5.565839       2.044725   
min         1.440000       0.000000      83.460000       0.010000   
25%        18.190000       0.000000      85.640000       2.400000   
50%        30.880000       0.000000      96.350000       3.380000   
75%        47.880000       0.000000      97.450000       4.680000   
max       100.000000      12.700000      99.820000      19.860000   

               WS50M  
count  525960.000000  
mean        5.401488  
std         2.748999  
min         0.000000  
25%         3.330000  
50%         5.110000  
75%         7.190000  
max        24.240000

There is a value that catches my attention in columns 5, 6, 7 and 8 where the minimum is -999.00. I need to figure out what to do with these values that don't seem to be correct.

In [356]:
# Take a look at the count of unique values, there are 3 unique values for STATE, which is what I expected.

df.nunique()

YEAR                      21
MO                        12
DY                        31
HR                        24
ALLSKY_SFC_SW_DWN      91755
CLRSKY_SFC_PAR_TOT     19155
ALLSKY_SFC_UV_INDEX      552
CLRSKY_SFC_SW_DWN      43369
WS2M                    1248
STATE                      3
T2M                     5544
T2MDEW                  4575
RH2M                    1578
PRECTOTCORR              366
PS                       871
WS10M                   1647
WS50M                   2004
dtype: int64

In [357]:
# Take a look at the first 20 lines

df.head(20)

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0   2003  10  31  16              15.90                6.48   
1   2003  10  31  17               0.00                0.00   
2   2003  10  31  18               0.00                0.00   
3   2003  10  31  19               0.00                0.00   
4   2003  10  31  20               0.00                0.00   
5   2003  10  31  21               0.00                0.00   
6   2003  10  31  22               0.00                0.00   
7   2003  10  31  23               0.00                0.00   
8   2003  11   1   0               0.00                0.00   
9   2003  11   1   1               0.00                0.00   
10  2003  11   1   2               0.00                0.00   
11  2003  11   1   3               0.00                0.00   
12  2003  11   1   4               0.00                0.00   
13  2003  11   1   5               0.00                0.00   
14  2003  11   1   6              51.18               37.48   
15  2003  11   1   7             149.51              125.65   
16  2003  11   1   8             240.25              209.45   
17  2003  11   1   9             351.60              273.08   
18  2003  11   1  10             393.48              310.52   
19  2003  11   1  11             429.77              314.35   

    ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M    STATE    T2M  T2MDEW  \
0                  0.02              15.77  5.09  Arizona  22.40    7.67   
1                  0.00               0.00  3.71  Arizona  20.98    8.09   
2                  0.00               0.00  2.62  Arizona  19.93    8.45   
3                  0.00               0.00  1.94  Arizona  19.12    8.76   
4                  0.00               0.00  1.51  Arizona  18.56    9.12   
5                  0.00               0.00  1.18  Arizona  18.19    9.54   
6                  0.00               0.00  0.99  Arizona  17.97   10.02   
7                  0.00               0.00  0.96  Arizona  17.75   10.58   
8                  0.00               0.00  1.10  Arizona  17.48   11.20   
9                  0.00               0.00  1.28  Arizona  17.22   11.83   
10                 0.00               0.00  1.37  Arizona  16.89   12.20   
11                 0.00               0.00  1.41  Arizona  16.50   12.03   
12                 0.00               0.00  1.49  Arizona  16.05   11.35   
13                 0.00               0.00  1.64  Arizona  15.57   10.40   
14                 0.05              88.27  2.12  Arizona  15.37    9.24   
15                 0.45             280.33  2.71  Arizona  16.18    7.59   
16                 1.33             462.55  2.78  Arizona  18.44    5.20   
17                 2.58             602.08  3.03  Arizona  20.67    3.77   
18                 3.33             684.50  3.36  Arizona  22.26    2.58   
19                 3.60             695.60  3.60  Arizona  23.40    1.73   

     RH2M  PRECTOTCORR     PS  WS10M  WS50M  
0   38.69         0.00  96.13   6.99   9.18  
1   43.38         0.00  96.19   5.23   7.72  
2   47.50         0.00  96.25   3.80   6.35  
3   51.06         0.00  96.30   2.95   5.56  
4   54.19         0.00  96.32   2.45   4.83  
5   57.06         0.00  96.33   2.11   4.06  
6   59.81         0.00  96.31   1.91   3.43  
7   62.94         0.01  96.29   1.87   3.29  
8   66.69         0.01  96.28   2.11   3.78  
9   70.56         0.03  96.27   2.26   4.29  
10  73.88         0.04  96.28   2.28   4.50  
11  75.12         0.05  96.28   2.27   4.57  
12  74.31         0.01  96.31   2.32   4.64  
13  72.25         0.01  96.36   2.48   4.72  
14  67.81         0.00  96.42   3.00   4.56  
15  57.50         0.00  96.47   3.49   3.91  
16  42.06         0.01  96.53   3.44   3.77  
17  32.94         0.01  96.54   3.72   4.06  
18  27.38         0.01  96.53   4.11   4.51  
19  24.06         0.01  96.47   4.43   4.87

**Looking for Missing Values**

In [358]:
# Find how many have null values

df.isna().sum()

YEAR                   0
MO                     0
DY                     0
HR                     0
ALLSKY_SFC_SW_DWN      0
CLRSKY_SFC_PAR_TOT     0
ALLSKY_SFC_UV_INDEX    0
CLRSKY_SFC_SW_DWN      0
WS2M                   0
STATE                  0
T2M                    0
T2MDEW                 0
RH2M                   0
PRECTOTCORR            0
PS                     0
WS10M                  0
WS50M                  0
dtype: int64

There is no missing data in any of the columns

**Cleaning Data**

I'll need to create a date column with the year, month, day and time columns

In [359]:

# Combine year, month, day, and hour into a single datetime column
df['DATE'] = pd.to_datetime(df[['YEAR', 'MO', 'DY']].astype(str).agg('-'.join, axis=1) + ' ' + df['HR'].astype(str) + ':00:00')

# Display the updated DataFrame
df.head()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
0  2003  10  31  16               15.9                6.48   
1  2003  10  31  17                0.0                0.00   
2  2003  10  31  18                0.0                0.00   
3  2003  10  31  19                0.0                0.00   
4  2003  10  31  20                0.0                0.00   

   ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M    STATE    T2M  T2MDEW  \
0                 0.02              15.77  5.09  Arizona  22.40    7.67   
1                 0.00               0.00  3.71  Arizona  20.98    8.09   
2                 0.00               0.00  2.62  Arizona  19.93    8.45   
3                 0.00               0.00  1.94  Arizona  19.12    8.76   
4                 0.00               0.00  1.51  Arizona  18.56    9.12   

    RH2M  PRECTOTCORR     PS  WS10M  WS50M                DATE  
0  38.69          0.0  96.13   6.99   9.18 2003-10-31 16:00:00  
1  43.38          0.0  96.19   5.23   7.72 2003-10-31 17:00:00  
2  47.50          0.0  96.25   3.80   6.35 2003-10-31 18:00:00  
3  51.06          0.0  96.30   2.95   5.56 2003-10-31 19:00:00  
4  54.19          0.0  96.32   2.45   4.83 2003-10-31 20:00:00

In [360]:
# Check the change

df.dtypes

YEAR                            int64
MO                              int64
DY                              int64
HR                              int64
ALLSKY_SFC_SW_DWN             float64
CLRSKY_SFC_PAR_TOT            float64
ALLSKY_SFC_UV_INDEX           float64
CLRSKY_SFC_SW_DWN             float64
WS2M                          float64
STATE                          object
T2M                           float64
T2MDEW                        float64
RH2M                          float64
PRECTOTCORR                   float64
PS                            float64
WS10M                         float64
WS50M                         float64
DATE                   datetime64[ns]
dtype: object

In [361]:
# Check the shape of the data set

df.shape

(525960, 18)

In [362]:
# Take a look at max, min and other information provided in describe

df.describe()

YEAR             MO             DY             HR  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean     2013.331090       6.522930      15.729637      11.500000   
min      2003.000000       1.000000       1.000000       0.000000   
25%      2008.000000       4.000000       8.000000       5.750000   
50%      2013.000000       7.000000      16.000000      11.500000   
75%      2018.000000      10.000000      23.000000      17.250000   
max      2023.000000      12.000000      31.000000      23.000000   
std         5.778417       3.448706       8.800100       6.922193   

       ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  ALLSKY_SFC_UV_INDEX  \
count      525960.000000       525960.000000        525960.000000   
mean          224.936379           99.053385           -17.001283   
min          -999.000000         -999.000000          -999.000000   
25%             0.000000            0.000000             0.000000   
50%             9.400000            2.770000             0.000000   
75%           489.825000          243.080000             2.350000   
max          1084.630000          471.120000            14.580000   
std           357.748778          208.190129           135.416708   

       CLRSKY_SFC_SW_DWN           WS2M            T2M         T2MDEW  \
count      525960.000000  525960.000000  525960.000000  525960.000000   
mean          245.863993       2.616128      20.575514       1.835372   
min          -999.000000       0.010000     -15.770000     -25.220000   
25%             0.000000       1.380000      12.370000      -4.430000   
50%             7.750000       2.170000      20.390000       1.220000   
75%           551.500000       3.490000      28.570000       8.020000   
max          1113.900000      14.810000      50.220000      25.850000   
std           376.746138       1.646024      10.702683       8.347475   

                RH2M    PRECTOTCORR             PS          WS10M  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean       35.020759       0.019436      93.187504       3.764486   
min         1.440000       0.000000      83.460000       0.010000   
25%        18.190000       0.000000      85.640000       2.400000   
50%        30.880000       0.000000      96.350000       3.380000   
75%        47.880000       0.000000      97.450000       4.680000   
max       100.000000      12.700000      99.820000      19.860000   
std        21.047573       0.131012       5.565839       2.044725   

               WS50M                           DATE  
count  525960.000000                         525960  
mean        5.401488  2013-10-31 03:49:59.999999744  
min         0.000000            2003-10-31 16:00:00  
25%         3.330000            2008-10-30 22:00:00  
50%         5.110000            2013-10-31 04:00:00  
75%         7.190000            2018-10-31 10:00:00  
max        24.240000            2023-10-31 16:00:00  
std         2.748999                            NaN

In [363]:
# Set the DATE column as the index of the DataFrame
df.set_index("DATE", inplace=True)

In [364]:
# Take a look at first 5 lines

df.head()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
DATE                                                                           
2003-10-31 16:00:00  2003  10  31  16               15.9                6.48   
2003-10-31 17:00:00  2003  10  31  17                0.0                0.00   
2003-10-31 18:00:00  2003  10  31  18                0.0                0.00   
2003-10-31 19:00:00  2003  10  31  19                0.0                0.00   
2003-10-31 20:00:00  2003  10  31  20                0.0                0.00   

                     ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M    STATE  \
DATE                                                                         
2003-10-31 16:00:00                 0.02              15.77  5.09  Arizona   
2003-10-31 17:00:00                 0.00               0.00  3.71  Arizona   
2003-10-31 18:00:00                 0.00               0.00  2.62  Arizona   
2003-10-31 19:00:00                 0.00               0.00  1.94  Arizona   
2003-10-31 20:00:00                 0.00               0.00  1.51  Arizona   

                       T2M  T2MDEW   RH2M  PRECTOTCORR     PS  WS10M  WS50M  
DATE                                                                         
2003-10-31 16:00:00  22.40    7.67  38.69          0.0  96.13   6.99   9.18  
2003-10-31 17:00:00  20.98    8.09  43.38          0.0  96.19   5.23   7.72  
2003-10-31 18:00:00  19.93    8.45  47.50          0.0  96.25   3.80   6.35  
2003-10-31 19:00:00  19.12    8.76  51.06          0.0  96.30   2.95   5.56  
2003-10-31 20:00:00  18.56    9.12  54.19          0.0  96.32   2.45   4.83

In [365]:
# And a look at the last 5 lines

df.tail()

YEAR  MO  DY  HR  ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  \
DATE                                                                           
2023-10-31 12:00:00  2023  10  31  12             -999.0              -999.0   
2023-10-31 13:00:00  2023  10  31  13             -999.0              -999.0   
2023-10-31 14:00:00  2023  10  31  14             -999.0              -999.0   
2023-10-31 15:00:00  2023  10  31  15             -999.0              -999.0   
2023-10-31 16:00:00  2023  10  31  16             -999.0              -999.0   

                     ALLSKY_SFC_UV_INDEX  CLRSKY_SFC_SW_DWN  WS2M      STATE  \
DATE                                                                           
2023-10-31 12:00:00               -999.0             -999.0  4.12  NewMexico   
2023-10-31 13:00:00               -999.0             -999.0  3.95  NewMexico   
2023-10-31 14:00:00               -999.0             -999.0  3.86  NewMexico   
2023-10-31 15:00:00               -999.0             -999.0  3.73  NewMexico   
2023-10-31 16:00:00               -999.0             -999.0  3.33  NewMexico   

                       T2M  T2MDEW   RH2M  PRECTOTCORR     PS  WS10M  WS50M  
DATE                                                                         
2023-10-31 12:00:00  13.62   -7.60  22.31          0.0  86.17   5.19   5.67  
2023-10-31 13:00:00  14.47   -8.50  19.62          0.0  86.10   4.98   5.40  
2023-10-31 14:00:00  14.75   -9.45  17.88          0.0  86.05   4.89   5.29  
2023-10-31 15:00:00  14.39  -10.28  17.19          0.0  86.03   4.81   5.26  
2023-10-31 16:00:00  13.16  -10.67  18.06          0.0  86.04   4.49   5.29

In [366]:
# I need to see which rows have the value of -999.0

# Replace -999 with the value you're searching for
value_to_find = -999.0

# Count occurrences of the value in any column
count_of_occurrences = (df == value_to_find).sum().sum()

# Display the count
print(f'The number of occurrences of {value_to_find} in any column is: {count_of_occurrences}')


The number of occurrences of -999.0 in any column is: 36379


In [367]:
# Print DATE values of rows to be dropped

rows_to_drop = df[df.eq(-999.0).any(axis=1)].index.tolist()
max_time = df.loc[rows_to_drop].index.max()
min_time = df.loc[rows_to_drop].index.min()
unique = df.loc[rows_to_drop].index.unique()

print("\nMax TIME value of rows to be dropped:", max_time)
print("Min TIME value of rows to be dropped:", min_time)
print("unique values:", unique)


Max TIME value of rows to be dropped: 2023-10-31 16:00:00
Min TIME value of rows to be dropped: 2003-11-19 12:00:00
unique values: DatetimeIndex(['2003-11-19 12:00:00', '2004-01-29 10:00:00',
               '2004-01-29 11:00:00', '2004-02-01 11:00:00',
               '2004-02-13 11:00:00', '2004-03-07 11:00:00',
               '2004-03-09 11:00:00', '2004-03-10 10:00:00',
               '2004-03-26 10:00:00', '2004-03-26 11:00:00',
               ...
               '2022-05-09 11:00:00', '2022-05-30 09:00:00',
               '2022-06-06 11:00:00', '2022-07-17 09:00:00',
               '2023-04-15 10:00:00', '2023-04-20 10:00:00',
               '2023-04-20 11:00:00', '2023-04-21 10:00:00',
               '2023-04-27 10:00:00', '2023-10-31 16:00:00'],
              dtype='datetime64[ns]', name='DATE', length=3888, freq=None)


I'll replace the -999 values with the surrounding average (1 hour before and 1 hour after)

In [368]:
# Replace -999 with NaN to average
df.replace(-999.0, np.nan, inplace=True)

# Iterate through columns
for col in ['ALLSKY_SFC_SW_DWN', 'CLRSKY_SFC_PAR_TOT', 'CLRSKY_SFC_PAR_TOT', 'CLRSKY_SFC_SW_DWN']:
    # Group by the hour of the day and fill NaN with the mean of each group
    df[col] = df.groupby(df.index.hour)[col].transform(lambda x: x.fillna(x.mean()))

# Display the describe function for the DataFrame with NaN replaced by the mean of the corresponding group. Take a look at max, min, and other information provided in describe
df.describe()


YEAR             MO             DY             HR  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean     2013.331090       6.522930      15.729637      11.500000   
std         5.778417       3.448706       8.800100       6.922193   
min      2003.000000       1.000000       1.000000       0.000000   
25%      2008.000000       4.000000       8.000000       5.750000   
50%      2013.000000       7.000000      16.000000      11.500000   
75%      2018.000000      10.000000      23.000000      17.250000   
max      2023.000000      12.000000      31.000000      23.000000   

       ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  ALLSKY_SFC_UV_INDEX  \
count      525960.000000       525960.000000        516149.000000   
mean          245.897696          117.858811             1.664624   
std           322.229829          151.789178             2.810749   
min             0.000000            0.000000             0.000000   
25%             0.000000            0.000000             0.000000   
50%            13.845000            4.730000             0.000000   
75%           498.550000          246.270000             2.420000   
max          1084.630000          471.120000            14.580000   

       CLRSKY_SFC_SW_DWN           WS2M            T2M         T2MDEW  \
count      525960.000000  525960.000000  525960.000000  525960.000000   
mean          267.183719       2.616128      20.575514       1.835372   
std           342.297073       1.646024      10.702683       8.347475   
min             0.000000       0.010000     -15.770000     -25.220000   
25%             0.000000       1.380000      12.370000      -4.430000   
50%            12.480000       2.170000      20.390000       1.220000   
75%           558.800000       3.490000      28.570000       8.020000   
max          1113.900000      14.810000      50.220000      25.850000   

                RH2M    PRECTOTCORR             PS          WS10M  \
count  525960.000000  525960.000000  525960.000000  525960.000000   
mean       35.020759       0.019436      93.187504       3.764486   
std        21.047573       0.131012       5.565839       2.044725   
min         1.440000       0.000000      83.460000       0.010000   
25%        18.190000       0.000000      85.640000       2.400000   
50%        30.880000       0.000000      96.350000       3.380000   
75%        47.880000       0.000000      97.450000       4.680000   
max       100.000000      12.700000      99.820000      19.860000   

               WS50M  
count  525960.000000  
mean        5.401488  
std         2.748999  
min         0.000000  
25%         3.330000  
50%         5.110000  
75%         7.190000  
max        24.240000

In [369]:
# Find how many have null values

df.isna().sum()

YEAR                      0
MO                        0
DY                        0
HR                        0
ALLSKY_SFC_SW_DWN         0
CLRSKY_SFC_PAR_TOT        0
ALLSKY_SFC_UV_INDEX    9811
CLRSKY_SFC_SW_DWN         0
WS2M                      0
STATE                     0
T2M                       0
T2MDEW                    0
RH2M                      0
PRECTOTCORR               0
PS                        0
WS10M                     0
WS50M                     0
dtype: int64

In [370]:
# Now see how many rows have the value of -999.0

# Replace -999 with the value you're searching for
value_to_find = -999.0

# Count occurrences of the value in any column
count_of_occurrences = (df == value_to_find).sum().sum()

# Display the count
print(f'The number of occurrences of {value_to_find} in any column is: {count_of_occurrences}')


The number of occurrences of -999.0 in any column is: 0


#### Drop the variable ALLSKY_SFC_UV_INDEX since it has too many missing values and it's very similar to the other 3 variables

In [371]:

df.drop('ALLSKY_SFC_UV_INDEX', axis=1, inplace=True)


We've taken care of all -999.0 values

In [372]:
# I will drop the columns YEAR, MO, DY, HR since I already incorporated it into the TIME variable.

df = df.drop(columns=['YEAR','MO','DY','HR'])
df.tail()

ALLSKY_SFC_SW_DWN  CLRSKY_SFC_PAR_TOT  CLRSKY_SFC_SW_DWN  \
DATE                                                                            
2023-10-31 12:00:00         775.887039          373.409582         844.988978   
2023-10-31 13:00:00         699.467639          338.641388         765.983423   
2023-10-31 14:00:00         568.029805          277.836721         628.367660   
2023-10-31 15:00:00         399.133650          196.251596         445.082981   
2023-10-31 16:00:00         216.608862          106.463195         243.502364   

                     WS2M      STATE    T2M  T2MDEW   RH2M  PRECTOTCORR  \
DATE                                                                      
2023-10-31 12:00:00  4.12  NewMexico  13.62   -7.60  22.31          0.0   
2023-10-31 13:00:00  3.95  NewMexico  14.47   -8.50  19.62          0.0   
2023-10-31 14:00:00  3.86  NewMexico  14.75   -9.45  17.88          0.0   
2023-10-31 15:00:00  3.73  NewMexico  14.39  -10.28  17.19          0.0   
2023-10-31 16:00:00  3.33  NewMexico  13.16  -10.67  18.06          0.0   

                        PS  WS10M  WS50M  
DATE                                      
2023-10-31 12:00:00  86.17   5.19   5.67  
2023-10-31 13:00:00  86.10   4.98   5.40  
2023-10-31 14:00:00  86.05   4.89   5.29  
2023-10-31 15:00:00  86.03   4.81   5.26  
2023-10-31 16:00:00  86.04   4.49   5.29

In [373]:
# I will drop first month of data and last 3 months of the data

# Specify the start and end dates for the period you want to keep
start_date = df.index.min() + pd.DateOffset(months=1)
end_date = df.index.max() - pd.DateOffset(months=4)

# Filter the DataFrame to keep rows within the specified period
df = df[(df.index >= start_date) & (df.index <= end_date)]


In [374]:
# Save DataFrame to a CSV file after data wrangling process:

df.to_csv('df.csv', index=True)
